"""
Export to Commercial Finite Element Analysis Software

Provides export capabilities for:
- Abaqus (.inp)
- ANSYS (.dat, .cdb)
- COMSOL (.mph - via geometry export)
- Gmsh (.msh)
- LAMMPS (.lmp)

References:
- Abaqus Documentation: https://help.3ds.com/
- ANSYS Documentation: https://www.ansys.com/
- Gmsh: https://gmsh.info/
"""

import numpy as np
from pathlib import Path
from typing import Union, Optional
from fibernet.core.network import FiberNetwork


def export_to_abaqus(
    network: FiberNetwork,
    filename: Union[str, Path],
    job_name: str = "FiberNetwork",
    material_name: str = "FIBER_MATERIAL",
    segments_per_fiber: int = 5,
    beam_type: str = "B31",
    element_size: float = 1.0,
) -> None:
    """
    Export fiber network to Abaqus input file (.inp).
    
    Parameters
    ----------
    network : FiberNetwork
        Fiber network to export
    filename : str or Path
        Output filename (should end with .inp)
    job_name : str
        Abaqus job name
    material_name : str
        Material name in Abaqus
    segments_per_fiber : int
        Number of beam elements per fiber
    beam_type : str
        Beam element type (B31, B32, B33)
    element_size : float
        Target element size
    
    Examples
    --------
    >>> from fibernet import gen
    >>> from fibernet.io.fea_export import export_to_abaqus
    >>> 
    >>> net = gen.random_straight_3d(num_fibers=50, box_size=(50, 50, 50))
    >>> export_to_abaqus(net, "network.inp", job_name="fiber_analysis")
    """
    path = Path(filename)
    
    with open(path, 'w') as f:
        # Header
        f.write(f"*HEADING\n")
        f.write(f"** Abaqus Input File Generated by FiberNet\n")
        f.write(f"** Network: {len(network.fibers)} fibers\n")
        f.write(f"** Job Name: {job_name}\n")
        f.write(f"**\n")
        
        # Part definition
        f.write(f"*PART, NAME=FIBER_NETWORK\n")
        
        # Nodes
        f.write(f"*NODE\n")
        node_id = 1
        node_map = {}  # Map (fiber_id, segment_id) -> node_id
        
        for fiber_idx, fiber in enumerate(network.fibers):
            # Generate nodes along fiber
            for seg_id in range(segments_per_fiber + 1):
                t = seg_id / segments_per_fiber
                # Linear interpolation
                position = fiber.start_point + t * (fiber.end_point - fiber.start_point)
                f.write(f"{node_id}, {position[0]:.6f}, {position[1]:.6f}, {position[2]:.6f}\n")
                node_map[(fiber_idx, seg_id)] = node_id
                node_id += 1
        
        # Elements
        f.write(f"*ELEMENT, TYPE={beam_type}, ELSET=ALL_FIBERS\n")
        element_id = 1
        for fiber_idx in range(len(network.fibers)):
            for seg_id in range(segments_per_fiber):
                node1 = node_map[(fiber_idx, seg_id)]
                node2 = node_map[(fiber_idx, seg_id + 1)]
                f.write(f"{element_id}, {node1}, {node2}\n")
                element_id += 1
        
        # Beam sections
        f.write(f"*BEAM SECTION, SECTION=CIRC, ELSET=ALL_FIBERS, MATERIAL={material_name}\n")
        if len(network.fibers) > 0:
            radius = network.fibers[0].radius
            f.write(f"{radius:.6f}\n")
        else:
            f.write(f"0.5\n")
        f.write(f"0.0, 0.0, 1.0\n")  # Beam orientation
        
        f.write(f"*END PART\n")
        f.write(f"**\n")
        
        # Assembly
        f.write(f"*ASSEMBLY, NAME=ASSEMBLY\n")
        f.write(f"*INSTANCE, NAME=FIBER_NETWORK-1, PART=FIBER_NETWORK\n")
        f.write(f"*END INSTANCE\n")
        f.write(f"*END ASSEMBLY\n")
        f.write(f"**\n")
        
        # Material definition
        f.write(f"*MATERIAL, NAME={material_name}\n")
        f.write(f"*ELASTIC\n")
        if len(network.fibers) > 0 and network.fibers[0].material is not None:
            E = network.fibers[0].material.youngs_modulus
            nu = network.fibers[0].material.poissons_ratio
            f.write(f"{E:.2e}, {nu:.3f}\n")
        else:
            f.write(f"1.0e9, 0.3\n")  # Default values
        
        f.write(f"*DENSITY\n")
        if len(network.fibers) > 0 and network.fibers[0].material is not None:
            rho = network.fibers[0].material.density
            f.write(f"{rho:.2f}\n")
        else:
            f.write(f"1000.0\n")
        
        f.write(f"**\n")
        
        # Step definition
        f.write(f"*STEP, NAME=StaticAnalysis\n")
        f.write(f"*STATIC\n")
        f.write(f"0.1, 1.0, 1e-5, 0.1\n")
        f.write(f"**\n")
        
        # Boundary conditions (fix first node)
        f.write(f"*BOUNDARY\n")
        f.write(f"ASSEMBLY.FIBER_NETWORK-1.1, ENCASTRE\n")
        f.write(f"**\n")
        
        # Output requests
        f.write(f"*OUTPUT, FIELD\n")
        f.write(f"*NODE OUTPUT\n")
        f.write(f"U, RF\n")
        f.write(f"*ELEMENT OUTPUT\n")
        f.write(f"S, E\n")
        f.write(f"**\n")
        
        f.write(f"*END STEP\n")


def export_to_ansys(
    network: FiberNetwork,
    filename: Union[str, Path],
    segments_per_fiber: int = 5,
    element_type: str = "BEAM188",
) -> None:
    """
    Export fiber network to ANSYS input file (.dat or .cdb).
    
    Parameters
    ----------
    network : FiberNetwork
        Fiber network to export
    filename : str or Path
        Output filename
    segments_per_fiber : int
        Number of beam elements per fiber
    element_type : str
        ANSYS element type (BEAM188, BEAM189)
    
    Examples
    --------
    >>> from fibernet import gen
    >>> from fibernet.io.fea_export import export_to_ansys
    >>> 
    >>> net = gen.random_straight_3d(num_fibers=50, box_size=(50, 50, 50))
    >>> export_to_ansys(net, "network.dat")
    """
    path = Path(filename)
    
    with open(path, 'w') as f:
        f.write(f"! ANSYS Input File Generated by FiberNet\n")
        f.write(f"! Network: {len(network.fibers)} fibers\n")
        f.write(f"!\n")
        
        # Preprocessor
        f.write(f"/PREP7\n")
        f.write(f"!\n")
        
        # Element type
        f.write(f"ET, 1, {element_type}\n")
        f.write(f"!\n")
        
        # Material properties
        if len(network.fibers) > 0 and network.fibers[0].material is not None:
            E = network.fibers[0].material.youngs_modulus
            nu = network.fibers[0].material.poissons_ratio
            rho = network.fibers[0].material.density
            radius = network.fibers[0].radius
        else:
            E, nu, rho, radius = 1.0e9, 0.3, 1000.0, 0.5
        
        f.write(f"MP, EX, 1, {E:.2e}\n")
        f.write(f"MP, PRXY, 1, {nu:.3f}\n")
        f.write(f"MP, DENS, 1, {rho:.2f}\n")
        f.write(f"!\n")
        
        # Beam section
        f.write(f"SECTYPE, 1, BEAM, CIRC\n")
        f.write(f"SECDATA, {radius:.6f}\n")
        f.write(f"!\n")
        
        # Nodes
        node_id = 1
        node_map = {}
        
        for fiber_idx, fiber in enumerate(network.fibers):
            for seg_id in range(segments_per_fiber + 1):
                t = seg_id / segments_per_fiber
                position = fiber.start_point + t * (fiber.end_point - fiber.start_point)
                f.write(f"N, {node_id}, {position[0]:.6f}, {position[1]:.6f}, {position[2]:.6f}\n")
                node_map[(fiber_idx, seg_id)] = node_id
                node_id += 1
        
        f.write(f"!\n")
        
        # Elements
        element_id = 1
        for fiber_idx in range(len(network.fibers)):
            for seg_id in range(segments_per_fiber):
                node1 = node_map[(fiber_idx, seg_id)]
                node2 = node_map[(fiber_idx, seg_id + 1)]
                f.write(f"E, {node1}, {node2}\n")
                element_id += 1
        
        f.write(f"!\n")
        
        # Boundary conditions
        f.write(f"D, 1, ALL, 0\n")  # Fix first node
        f.write(f"!\n")
        
        f.write(f"FINISH\n")
        f.write(f"!\n")
        
        # Solution
        f.write(f"/SOLU\n")
        f.write(f"ANTYPE, STATIC\n")
        f.write(f"SOLVE\n")
        f.write(f"FINISH\n")
        f.write(f"!\n")
        
        # Post-processing
        f.write(f"/POST1\n")
        f.write(f"PLNSOL, U, SUM\n")
        f.write(f"FINISH\n")


def export_to_gmsh(
    network: FiberNetwork,
    filename: Union[str, Path],
    segments_per_fiber: int = 5,
) -> None:
    """
    Export fiber network to Gmsh format (.msh).
    
    Parameters
    ----------
    network : FiberNetwork
        Fiber network to export
    filename : str or Path
        Output filename
    segments_per_fiber : int
        Number of segments per fiber
    
    Examples
    --------
    >>> from fibernet import gen
    >>> from fibernet.io.fea_export import export_to_gmsh
    >>> 
    >>> net = gen.random_straight_3d(num_fibers=50, box_size=(50, 50, 50))
    >>> export_to_gmsh(net, "network.msh")
    """
    path = Path(filename)
    
    with open(path, 'w') as f:
        # Gmsh format header
        f.write(f"$MeshFormat\n")
        f.write(f"4.1 0 8\n")
        f.write(f"$EndMeshFormat\n")
        f.write(f"\n")
        
        # Nodes
        f.write(f"$Nodes\n")
        
        # Count total nodes
        total_nodes = len(network.fibers) * (segments_per_fiber + 1)
        f.write(f"1 {total_nodes} 1 {total_nodes}\n")
        f.write(f"1 3 {total_nodes}\n")
        
        node_id = 1
        node_map = {}
        
        for fiber_idx, fiber in enumerate(network.fibers):
            for seg_id in range(segments_per_fiber + 1):
                t = seg_id / segments_per_fiber
                position = fiber.start_point + t * (fiber.end_point - fiber.start_point)
                f.write(f"{node_id} {position[0]:.6f} {position[1]:.6f} {position[2]:.6f}\n")
                node_map[(fiber_idx, seg_id)] = node_id
                node_id += 1
        
        f.write(f"$EndNodes\n")
        f.write(f"\n")
        
        # Elements (lines)
        f.write(f"$Elements\n")
        total_elements = len(network.fibers) * segments_per_fiber
        f.write(f"1 {total_elements} 1 {total_elements}\n")
        f.write(f"1 1 {total_elements}\n")
        
        element_id = 1
        for fiber_idx in range(len(network.fibers)):
            for seg_id in range(segments_per_fiber):
                node1 = node_map[(fiber_idx, seg_id)]
                node2 = node_map[(fiber_idx, seg_id + 1)]
                f.write(f"{element_id} {node1} {node2}\n")
                element_id += 1
        
        f.write(f"$EndElements\n")


def export_to_lammps(
    network: FiberNetwork,
    filename: Union[str, Path],
    atom_style: str = "bond",
    segments_per_fiber: int = 5,
) -> None:
    """
    Export fiber network to LAMMPS data file.
    
    Parameters
    ----------
    network : FiberNetwork
        Fiber network to export
    filename : str or Path
        Output filename
    atom_style : str
        LAMMPS atom style
    segments_per_fiber : int
        Number of segments per fiber
    
    Examples
    --------
    >>> from fibernet import gen
    >>> from fibernet.io.fea_export import export_to_lammps
    >>> 
    >>> net = gen.random_straight_3d(num_fibers=50, box_size=(50, 50, 50))
    >>> export_to_lammps(net, "network.lmp")
    """
    path = Path(filename)
    
    # Calculate bounds
    all_points = []
    for fiber in network.fibers:
        all_points.extend([fiber.start_point, fiber.end_point])
    all_points = np.array(all_points)
    
    if len(all_points) == 0:
        import warnings
        warnings.warn("No fibers to export")
        with open(path, 'w') as f:
            f.write("LAMMPS Data File Generated by FiberNet\n\n")
            f.write("0 atoms\n0 bonds\n0 angles\n0 dihedrals\n\n")
        return
    
    x_min, x_max = all_points[:, 0].min(), all_points[:, 0].max()
    y_min, y_max = all_points[:, 1].min(), all_points[:, 1].max()
    z_min, z_max = all_points[:, 2].min(), all_points[:, 2].max()
    
    with open(path, 'w') as f:
        f.write(f"LAMMPS Data File Generated by FiberNet\n")
        f.write(f"\n")
        
        # Counts
        num_atoms = len(network.fibers) * (segments_per_fiber + 1)
        num_bonds = len(network.fibers) * segments_per_fiber
        f.write(f"{num_atoms} atoms\n")
        f.write(f"{num_bonds} bonds\n")
        f.write(f"0 angles\n")
        f.write(f"0 dihedrals\n")
        f.write(f"0 impropers\n")
        f.write(f"\n")
        
        # Types
        f.write(f"1 atom types\n")
        f.write(f"1 bond types\n")
        f.write(f"0 angle types\n")
        f.write(f"0 dihedral types\n")
        f.write(f"0 improper types\n")
        f.write(f"\n")
        
        # Box bounds
        f.write(f"{x_min:.6f} {x_max:.6f} xlo xhi\n")
        f.write(f"{y_min:.6f} {y_max:.6f} ylo yhi\n")
        f.write(f"{z_min:.6f} {z_max:.6f} zlo zhi\n")
        f.write(f"\n")
        
        # Masses
        f.write(f"Masses\n")
        f.write(f"\n")
        if len(network.fibers) > 0 and network.fibers[0].material is not None:
            mass = network.fibers[0].material.density * 1.0  # Simplified
        else:
            mass = 1.0
        f.write(f"1 {mass:.6f}\n")
        f.write(f"\n")
        
        # Atoms
        f.write(f"Atoms\n")
        f.write(f"\n")
        
        atom_id = 1
        node_map = {}
        
        for fiber_idx, fiber in enumerate(network.fibers):
            mol_id = fiber_idx + 1
            for seg_id in range(segments_per_fiber + 1):
                t = seg_id / segments_per_fiber
                position = fiber.start_point + t * (fiber.end_point - fiber.start_point)
                f.write(f"{atom_id} {mol_id} 1 {position[0]:.6f} {position[1]:.6f} {position[2]:.6f}\n")
                node_map[(fiber_idx, seg_id)] = atom_id
                atom_id += 1
        
        f.write(f"\n")
        
        # Bonds
        f.write(f"Bonds\n")
        f.write(f"\n")
        
        bond_id = 1
        for fiber_idx in range(len(network.fibers)):
            for seg_id in range(segments_per_fiber):
                atom1 = node_map[(fiber_idx, seg_id)]
                atom2 = node_map[(fiber_idx, seg_id + 1)]
                f.write(f"{bond_id} 1 {atom1} {atom2}\n")
                bond_id += 1


