"""
PDB (Protein Data Bank) file format I/O.

Used for molecular visualization and compatibility with bioinformatics tools.
"""

import numpy as np
from fibernet.core.network import FiberNetwork
from fibernet.core.fiber import Fiber


def to_pdb(
    network: FiberNetwork,
    filename: str,
    bead_spacing: float = None,
    atom_name: str = "CA",
    residue_name: str = "FBR",
) -> str:
    """Export fiber network to PDB format.
    
    Parameters
    ----------
    network : FiberNetwork
        Fiber network.
    filename : str
        Output file path.
    bead_spacing : float
        Spacing between beads.
    atom_name : str
        PDB atom name.
    residue_name : str
        PDB residue name.
    """
    if bead_spacing is None:
        bead_spacing = network.mean_radius * 3
    
    with open(filename, 'w') as f:
        f.write(f"HEADER    FIBER NETWORK\n")
        f.write(f"REMARK    Generated by FiberNet\n")
        f.write(f"REMARK    {network.num_fibers} fibers\n")
        
        atom_id = 1
        residue_id = 1
        
        for f_idx, fiber in enumerate(network.fibers):
            length = fiber.length
            num_pts = max(2, int(length / bead_spacing) + 1)
            
            if num_pts == 2:
                pts = np.array([fiber.start_point, fiber.end_point])
            else:
                pts = fiber.resample(num_pts).centerline
            
            chain_id = chr(65 + (f_idx % 26))  # A-Z
            
            for pt in pts:
                # PDB coordinate convention (Å)
                x, y, z = pt * 10.0  # Convert to Å if in nm
                
                line = (
                    f"ATOM  {atom_id:5d} {atom_name:4s} {residue_name:3s} {chain_id:1s}"
                    f"{residue_id:4d}    "
                    f"{x:8.3f}{y:8.3f}{z:8.3f}"
                    f"  1.00  0.00\n"
                )
                f.write(line)
                atom_id += 1
                residue_id += 1
            
            # Connect atoms in fiber
            for i in range(num_pts - 1):
                f.write(f"CONECT{atom_id - num_pts + i:5d}{atom_id - num_pts + i + 1:5d}\n")
            
            f.write("TER\n")
        
        f.write("END\n")
    
    return filename


def from_pdb(filename: str, bead_radius: float = 0.1) -> FiberNetwork:
    """Import fiber network from PDB file.
    
    Reads CONECT records to reconstruct fiber chains.
    """
    atoms = {}
    conect = []
    
    with open(filename, 'r') as f:
        for line in f:
            if line.startswith("ATOM") or line.startswith("HETATM"):
                aid = int(line[6:11])
                x = float(line[30:38]) / 10.0  # Å to nm
                y = float(line[38:46]) / 10.0
                z = float(line[46:54]) / 10.0
                atoms[aid] = np.array([x, y, z])
            
            elif line.startswith("CONECT"):
                parts = line[6:].split()
                if len(parts) >= 2:
                    try:
                        i = int(parts[0])
                        j = int(parts[1])
                        conect.append((i, j))
                    except ValueError:
                        pass
    
    if not atoms:
        return FiberNetwork()
    
    adj = {}
    for i, j in conect:
        adj.setdefault(i, []).append(j)
        adj.setdefault(j, []).append(i)
    
    visited = set()
    chains = []
    
    for start in atoms:
        if start in visited:
            continue
        chain = [start]
        visited.add(start)
        current = start
        while True:
            neighbors = [n for n in adj.get(current, []) if n not in visited]
            if not neighbors:
                break
            nxt = neighbors[0]
            chain.append(nxt)
            visited.add(nxt)
            current = nxt
        if len(chain) >= 2:
            chains.append(chain)
    
    net = FiberNetwork(dimension=3)
    for c_idx, chain in enumerate(chains):
        positions = np.array([atoms[aid] for aid in chain])
        fiber = Fiber(centerline=positions, radius=bead_radius, fiber_id=c_idx)
        net.add_fiber(fiber)
    
    net.auto_crosslink(threshold=3.0 * bead_radius)
    return net
