from setuptools import setup, find_packages

setup(
    name="fibernet",
    version="0.3.0",
    packages=find_packages(),
    install_requires=[
        "numpy>=1.21",
        "scipy>=1.7",
    ],
    extras_require={
        "viz": ["pyvista>=0.37"],
        "io": ["h5py>=3.7"],
        "accel": ["taichi>=1.6"],
        "ml": ["scikit-learn>=1.0"],
        "full": [
            "pyvista>=0.37",
            "h5py>=3.7",
            "taichi>=1.6",
            "scikit-learn>=1.0",
        ],
        "dev": [
            "pytest>=7.0",
            "pytest-cov>=4.0",
            "sphinx>=7.0",
            "sphinx-rtd-theme>=2.0",
            "black>=23.0",
            "flake8>=6.0",
        ],
    },
    author="FiberNet Contributors",
    author_email="fibernet@example.com",
    description="A comprehensive fiber network generation and simulation toolkit",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/GellmanSparrowS/fibernet",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Scientific/Engineering",
        "Topic :: Scientific/Engineering :: Physics",
    ],
    python_requires=">=3.9",
)
